---
- name: Local addons playbook (login) 
  hosts: login
  roles:
  - { role: ansible-role-slurm-spank-gpu, tags: ['local', 'spank'] }
  - { role: ansible-role-apptainer, tags: ['apptainer', 'singularity'] }

